[package]
name = "toio_core_cube"
version = "0.34.0"
authors = ["yabe_z <Kazuhiro.Yabe@gmail.com>"]
edition = "2021"
license-file = "LICENSE"
keywords = [ "toio", "toio_core_cube" ]
description = "A small library for toio core cube"
repository = "https://github.com/kaz399/rs_toio_core_cube/"
homepage = "https://github.com/kaz399/rs_toio_core_cube/"

[dependencies]
futures = "0.3"
async-trait = "0.1.53"
thiserror = "1.0.30"
env_logger = "0.9.0"
log = "0.4.14"
uuid = { version = "0.8.2", features = ["v4"] }
tokio = { version = "1.17.0", features = ["rt", "sync", "macros"] }
btleplug = "0.9.2"

[dev-dependencies]
lazy_static = "1.4.0"
ctrlc = { version = "3.2.1", features = ["termination"] }
clap = "3.1.6"
rand = "0.8.5"
